schema = 1

[workspace]
name = "vapor-entrypoint"
organization = "ghf-studios"
version = "0.5.0"
repository = "https://github.com/GHF-Studios/Vapor-Entrypoint"

[toolchain]
channel = "stable"
version = "1.97.0"
date = "2026-07-09"

[[project]]
name = "vapor-entrypoint"
path = "."
